config/routes.rb
Perfectfit::Application.routes.draw do
  get "search/search"

  post "search/search"

  resources :measurements

  resources :products

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  attr_accessible :product_id, :color, :gender, :inseam,  :waist, :weight, :weight2, :height_feet, :height_inch, :height_feet2, :height_inch2, :image
  belongs_to :product
  mount_uploader :image, ImageUploader

=begin
  def self.search(search_color, search_gender, search_inseam, search_waist, search_hip, search_height, search_weight)
    return scoped unless search_color.present? || search_gender.present? || search_inseam.present? || search_waist.present? || search_hip.present? || search_height.present? || search_weight.present?
    where(['color LIKE ? AND gender LIKE ? AND inseam LIKE ? AND waist LIKE ? AND hips LIKE ? AND height LIKE ? AND weight LIKE ?',
           "%#{search_color}%", "%#{search_gender}%", "%#{search_inseam}%", "%#{search_waist}%", "%#{search_hip}%", "%#{search_height}%", "%#{search_weight}%"])
  end
=end

  def self.search(search_color, search_gender, search_height_feet, search_height_inch, search_weight)
    args = Hash["color" => search_color, "gender" => search_gender, "height_feet" => search_height_feet, "height_inch" => search_height_inch, "weight" => search_weight]
    cond_text, cond_values = [], []
    args.each do |key,value|
      next if value.blank?
      cond_text << "( %s )" % value.split.map{|w| key + " LIKE ? "}.join(" OR ")
      if value != search_color
        cond_values.concat(value.split.map{|w| w})
      else
        cond_values.concat(value.split.map{|w| "%#{w}%"})
      end
    end
    find( :all, :conditions =>  [cond_text.join(" AND "), *cond_values])
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :merchant, :name, :price
  has_many :measurements, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.search(params[:color],params[:gender],params[:height_feet],params[:height_inch],params[:weight])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @measurements }
    end
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/new
  # GET /measurements/new.json
  def new
    @measurement = Measurement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/1/edit
  def edit
    @measurement = Measurement.find(params[:id])
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(params[:measurement])

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render json: @measurement, status: :created, location: @measurement }
      else
        format.html { render action: "new" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /measurements/1
  # PUT /measurements/1.json
  def update
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      if @measurement.update_attributes(params[:measurement])
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement = Measurement.find(params[:id])
    @measurement.destroy

    respond_to do |format|
      format.html { redirect_to measurements_url }
      format.json { head :no_content }
    end
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index

    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

=begin
  def search
    #store all the parameters that match the search
    @merchant = Product.where("merchant LIKE ? ", "%#{params[:merchant]}%")
    @colors = Measurement.where("color LIKE ? ", "%#{params[:color]}%")
    @genders = Measurement.where("gender LIKE ? ", params[:gender])
=begin
    @genders = Measurement.where("gender LIKE ? ", "%#{params[:gender]}%")

    @inseams = Measurement.where("inseam LIKE ? ", "%#{params[:inseam]}%")
    @waists = Measurement.where("waist LIKE ? ", "%#{params[:waist]}%")
    @hips = Measurement.where("hip LIKE ? ", "%#{params[:hip]}%")
    @heights = Measurement.where("height LIKE ? ", "%#{params[:height]}%")
    @weights = Measurement.where("weight LIKE ? ", "%#{params[:weight]}%")
  end
=end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Perfectfit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


</body>
</html>

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <% all_products = Product.all %>
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += all_products.map { |c| [ c.name, c.id ] } %>
    <%= f.select :product_id, menu_items %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [['Male', 'Male'],['Female', 'Female']] %>
    <%= f.select :gender, menu_items %>
  </div>
  <div class="field">
    <%= f.label :inseam %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[30, 30],[31, 31],[32, 32],[33, 33],[34, 34],[35, 35]] %>
    <%= f.select :inseam, menu_items %>
  </div>
  <div class="field">
    <%= f.label :waist %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[23, 23],[24, 24],[25, 25],[26, 26],[27, 27],[28, 28],[29, 29],[30, 30],[31, 31],[32, 32],[33, 33],[34, 34],[35, 35],[36, 36],[37, 37],[38, 38],[39, 39],[40, 40],[41, 41],[42, 42],[43, 43]] %>
    <%= f.select :waist, menu_items %>
  </div>
  <div class="field">
    <%= f.label :height_feet %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[4, 4],[5, 5],[6, 6]] %>
    <%= f.select :height_feet, menu_items %>
  </div>
  <div class="field">
    <%= f.label :height_inch %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[0, 0],[1, 1],[2, 2],[3, 3],[4, 4],[5, 5],[6, 6],[7, 7],[8, 8],[9, 9],[10, 10],[11, 11]] %>
    <%= f.select :height_inch, menu_items %>
  </div>
  <div class="field">
    <%= f.label :height_feet2 %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[4, 4],[5, 5],[6, 6]] %>
    <%= f.select :height_feet2, menu_items %>
  </div>
  <div class="field">
    <%= f.label :height_inch2 %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[0, 0],[1, 1],[2, 2],[3, 3],[4, 4],[5, 5],[6, 6],[7, 7],[8, 8],[9, 9],[10, 10],[11, 11]] %>
    <%= f.select :height_inch2, menu_items %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[90, 90],[95, 95],[100, 100],[105, 105],[110, 110],[115, 115],[120, 120],[125, 125],[130, 130],[135, 135],[140, 140],[145, 145],[145, 145],[145, 145],[145, 145],[150, 150],[155, 155],[160, 160],[165, 165],[170, 170],[175, 175],[180, 180],[185, 185],[190, 190],[195, 195],[200, 200],[205, 205],[210, 210],[215, 215],[220, 220]] %>
    <%= f.select :weight, menu_items %>
  </div>
  <div class="field">
    <%= f.label :weight2 %><br />
    <% menu_items = [['Not decided', '']] %>
    <% menu_items += [[90, 90],[95, 95],[100, 100],[105, 105],[110, 110],[115, 115],[120, 120],[125, 125],[130, 130],[135, 135],[140, 140],[145, 145],[145, 145],[145, 145],[145, 145],[150, 150],[155, 155],[160, 160],[165, 165],[170, 170],[175, 175],[180, 180],[185, 185],[190, 190],[195, 195],[200, 200],[205, 205],[210, 210],[215, 215],[220, 220]] %>
    <%= f.select :weight2, menu_items %>
  </div>
  <div class="field">
    <%= f.label :measurement_image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<h1>Measurements</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Merchant</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>

<!--
  the following is to see all the measurements data from database
-->
    <th>delete right</th>
    <th>gender</th>
    <th>color</th>
    <th>inseam</th>
    <th>waist</th>
    <th>height(feet)</th>
    <th>height(inches)</th>
    <th>height(feet)2</th>
    <th>height(inches)2</th>
    <th>weight</th>
    <th>weight2</th>
    <th></th>
    <th></th>
    <th></th>
<!--
  rows until here
-->
  </tr>

<% @measurements.each do |measurement| %>
  <tr>
    <td><%= image_tag(measurement.image_url, :class => 'product-image') if measurement.image? %></td>
    <td><%= measurement.product.merchant %></td>
    <td><%= measurement.product.name%></td>
    <td><%= measurement.product.price %></td>
    <td><%= link_to 'Show', measurement %></td>
<!--
    <td><%= link_to 'Show', measurement.product %></td>
-->

<!--
  the following is to see all the measurements data from database
-->
    <td>delete right</td>
    <td><%= measurement.gender %></td>
    <td><%= measurement.color %></td>
    <td><%= measurement.inseam %></td>
    <td><%= measurement.waist %></td>
    <td><%= measurement.height_feet %></td>
    <td><%= measurement.height_inch %></td>
    <td><%= measurement.height_feet2 %></td>
    <td><%= measurement.height_inch2 %></td>
    <td><%= measurement.weight %></td>
    <td><%= measurement.weight2 %></td>
    <td><%= link_to 'Show', measurement %></td>
    <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
    <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<!--
  rows until here
-->

  </tr>

<% end %>
</table>

<br />

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product Image:</b>
  <%= image_tag @measurement.image_url if @measurement.image? %>
</p>

<p>
  <b>Merchant:</b>
  <%= @measurement.product.merchant %>
</p>

<p>
  <b>Product name:</b>
  <%= @measurement.product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @measurement.product.price %>
</p>

<p>
  <b>Color:</b>
  <%= @measurement.color %>
</p>

<p>
  <b>Inseam:</b>
  <%= @measurement.inseam %>
</p>

<p>
  <b>Waist:</b>
  <%= @measurement.waist %>
</p>

<!--
  the following is to see all the measurements data from database
-->
<p>
  delete the followings:
</p>

<p>
  <b>Gender:</b>
  <%= @measurement.gender %>
</p>

<p>
  <b>Range of height:</b>
  <%= @measurement.height_feet %> feet  <%= @measurement.height_inch %> inches
  to
  <%= @measurement.height_feet2 %> feet  <%= @measurement.height_inch2 %> inches
</p>

<p>
  <b>Range of weight:</b>
  <%= @measurement.weight %> to <%= @measurement.weight2 %> lbs
</p>
<!--
  data until here
-->

<div class="fb-comments" data-href="http://example.com/comments" data-numposts="5"></div>

<div class="fb-comments" data-href="http://localhost:3000/measurements/" data-numposts="5"></div>


<!--
<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>
-->

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :merchant %><br />
    <%= f.text_field :merchant %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <th>Merchant</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.merchant %></td>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Merchant:</b>
  <%= @product.merchant %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/search/search.html.erb
<h1>Search</h1>

<% if flash[:error] %>
    <div id="error_explanation">
      <%= flash[:error] %>
    </div>
<% end %>

<%= form_tag measurements_path, :method => 'get' do %>

    <p>
      Gender: <%= select_tag "gender", options_for_select( %w(Male Female), params[:gender]), :include_blank => true %>
    </p>
    <p>
      Color: <%= select_tag "color", options_for_select( %w(Blue Black), params[:color]), :include_blank => true %>
    </p>
    <p>
      Height:
      <%= select_tag "height_feet", options_for_select( %w(4 5 6), params[:height_feet]), :include_blank => true %> feet
      <%= select_tag "height_inch", options_for_select( %w(0 1 2 3 4 5 6 7 8 9 10 11), params[:height_inch]), :include_blank => true %> inches
    </p>
    <p>
      Weight:
      <%= select_tag "weight", options_for_select( %w(90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220), params[:weight]), :include_blank => true %> lbs
    </p>
    <p>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>



<!--
    <p>
      Weight:
      <%= select_tag "weight", options_for_select( Measurement.uniq.pluck(:weight), params[:weight]), :include_blank => true %> lbs
    </p>
 -->

app/views/search/update_colors.js.haml
$('#color_select').html("#{escape_javascript(options_for_select(@colors))}")